/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=WorkerBindings` (hash: 52c436b05bcd6768a4a46c35b73abc11)
interface __BaseEnv_WorkerBindings {
	ANALYTICS_DB: D1Database;
	ANALYTICS_RATE_LIMIT: RateLimit;
	ASSETS: Fetcher;
	FIREBASE_PROJECT_ID: "kilo-g";
	TURNSTILE_HOSTNAMES: "web-dev.pp.ua,kilo-g.web-developer-den.workers.dev";
	TURNSTILE_SECRET_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/index");
	}
	interface Env extends __BaseEnv_WorkerBindings {}
}
interface WorkerBindings extends __BaseEnv_WorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FIREBASE_PROJECT_ID" | "TURNSTILE_HOSTNAMES" | "TURNSTILE_SECRET_KEY">> {}
}
declare module "*.txt" {
	const value: string;
	export default value;
}
declare module "*.html" {
	const value: string;
	export default value;
}
declare module "*.sql" {
	const value: string;
	export default value;
}
declare module "*.bin" {
	const value: ArrayBuffer;
	export default value;
}
declare module "*.wasm" {
	const value: WebAssembly.Module;
	export default value;
}
declare module "*.wasm?module" {
	const value: WebAssembly.Module;
	export default value;
}