import { Inflate } from 'fflate';
import type { ParsedFilamentLayer, ParsedJob, ParsedPlate } from '../domain/types.ts';

// Supports Bambu/Orca slice_info.config and text G-code statistics, not binary G-code or slicing geometry.
// Format sources: BambuStudio/src/libslic3r/Format/bbs_3mf.cpp and PrusaSlicer/src/libslic3r/GCode.cpp.
export const FILE_SIZE_LIMIT = 50 * 1024 * 1024;
const ENTRY_SIZE_LIMIT = 64 * 1024 * 1024;
const ARCHIVE_SIZE_LIMIT = 256 * 1024 * 1024;
const METADATA_SIZE_LIMIT = 2 * 1024 * 1024;
const decoder = new TextDecoder('utf-8', { fatal: true });

class ParseFailure extends Error {
  constructor(public status: ParsedJob['parseStatus'], message: string) { super(message); }
}

function corrupt(): never { throw new ParseFailure('corrupted', 'Архів або його метадані пошкоджені.'); }
function incomplete(): never { throw new ParseFailure('error', 'Для розрахунку потрібні час друку та витрати кожного філаменту в грамах. Експортуйте файл після нарізки зі збереженими метаданими.'); }
function limit(): never { throw new ParseFailure('file_limit_exceeded', 'Файл перевищує ліміт: 50 МБ завантаження, 64 МБ на запис архіву, 256 МБ розпакованих даних та 2048 записів.'); }
const number = (value: string | undefined): number | undefined => {
  if (value === undefined || !/^\d+(?:\.\d+)?$/.test(value.trim())) return undefined;
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : undefined;
};

export function parseDuration(value: string | undefined): number | undefined {
  if (!value) return undefined;
  const text = value.trim();
  const seconds = number(text);
  if (seconds !== undefined) return seconds;
  if (/^\d+:\d{2}:\d{2}$/.test(text)) {
    const [h, m, s] = text.split(':').map(Number);
    return m < 60 && s < 60 ? h * 3600 + m * 60 + s : undefined;
  }
  if (!/^(?:\d+\s*d\s*)?(?:\d+\s*h\s*)?(?:\d+\s*m\s*)?(?:\d+\s*s\s*)?$/.test(text)) return undefined;
  const units: Record<string, number> = { d: 86400, h: 3600, m: 60, s: 1 };
  return [...text.matchAll(/(\d+)\s*([dhms])/g)].reduce((total, match) => total + Number(match[1]) * units[match[2]], 0);
}

const values = (value: string | undefined) => value?.split(/[;,]/).map((part) => part.trim().replace(/^"|"$/g, '')) ?? [];
const numbers = (value: string | undefined) => values(value).map(number);
const color = (value: string | undefined) => value && /^#[\da-f]{6}(?:[\da-f]{2})?$/i.test(value) ? value.slice(0, 7) : '#808080';
const massFromLength = (lengthMm: number | undefined, diameter: number | undefined, density: number | undefined) =>
  lengthMm !== undefined && diameter && density ? lengthMm * Math.PI * (diameter / 2) ** 2 * density / 1000 : undefined;

function plate(index: number, duration: number | undefined, filaments: ParsedFilamentLayer[]): ParsedPlate {
  if (!Number.isInteger(index) || index < 1 || !duration || !Number.isFinite(duration) || !filaments.length) incomplete();
  if (filaments.some((f) => !Number.isInteger(f.trayId) || f.trayId < 1 || !Number.isFinite(f.weightGrams) || f.weightGrams < 0)) incomplete();
  const totalWeightGrams = filaments.reduce((sum, f) => sum + f.weightGrams, 0);
  if (!totalWeightGrams || !Number.isFinite(totalWeightGrams) || new Set(filaments.map((f) => f.trayId)).size !== filaments.length) incomplete();
  return { plateIndex: index, plateName: `Пластина ${index}`, predictionSeconds: duration, totalWeightGrams, filaments: filaments.filter((f) => f.weightGrams > 0), selected: true, repeatsCount: 1 };
}

function parseGcode(text: string, index: number, archiveDuration?: number) {
  const meta: Record<string, string> = Object.create(null);
  for (const match of text.matchAll(/^;[ \t]*([^\r\n=]+?)[ \t]*=[ \t]*([^\r\n]*)\r?$/gm)) meta[match[1].trim()] = match[2].trim();
  const source = text.match(/^;\s*generated by\s+([^\r\n]+)/mi)?.[1] ?? 'G-code (метадані слайсера)';
  const duration = archiveDuration ?? parseDuration(meta['estimated printing time (normal mode)'] ?? text.match(/;\s*total estimated time:\s*([^;\r\n]+)/i)?.[1]);
  const types = values(meta.filament_type);
  const colors = values(meta.filament_colour ?? meta.filament_color);
  const packedWeights = text.match(/^;\s*total filament weight \[g\]\s*:\s*([^\r\n]+)/mi)?.[1];
  const weights = numbers(meta['filament used [g]'] ?? packedWeights);
  const lengths = numbers(meta['filament used [mm]'] ?? text.match(/^;\s*total filament length \[mm\]\s*:\s*([^\r\n]+)/mi)?.[1]);
  const diameters = numbers(meta.filament_diameter);
  const densities = numbers(meta.filament_density);
  // shortcut: packed Bambu G-code omits unused tray IDs; use slice_info.config when its array cannot be matched exactly.
  if (packedWeights && types.length > weights.length) incomplete();
  if (!weights.length && !lengths.length && types.length <= 1) weights.push(number(meta['total filament used [g]']));
  const count = Math.max(weights.length, lengths.length);
  if (!count || weights.some((weight) => weight === undefined) || lengths.some((length) => length === undefined)) incomplete();
  const filaments = Array.from({ length: count }, (_, i): ParsedFilamentLayer => {
    const mass = weights[i] ?? massFromLength(lengths[i], diameters[i] ?? (diameters.length === 1 ? diameters[0] : undefined), densities[i] ?? (densities.length === 1 ? densities[0] : undefined));
    if (mass === undefined || (lengths[i] && !mass)) incomplete();
    const length = lengths[i];
    return { trayId: i + 1, type: types[i] || 'Невідомий', colorHex: color(colors[i]), weightGrams: mass, ...(length !== undefined ? { lengthMeters: length / 1000 } : {}) };
  });
  return { plate: plate(index, duration, filaments), source, printer: meta.printer_model, nozzle: meta.nozzle_diameter };
}

function attributes(tag: string) {
  const attrs: Record<string, string> = Object.create(null);
  const content = tag.replace(/^<\/?[\w:.-]+/, '').replace(/\/?\s*>$/, '');
  const decode = (value: string) => value.replace(/&(amp|lt|gt|quot|apos|#\d+|#x[\da-f]+);/gi, (_, entity: string) => {
    const named: Record<string, string> = { amp: '&', lt: '<', gt: '>', quot: '"', apos: "'" };
    if (named[entity]) return named[entity];
    const code = entity.startsWith('#x') ? parseInt(entity.slice(2), 16) : Number(entity.slice(1));
    if (code <= 0 || code > 0x10ffff || code >= 0xd800 && code <= 0xdfff) corrupt();
    return String.fromCodePoint(code);
  });
  const rest = content.replace(/([\w:.-]+)\s*=\s*(?:"([^"]*)"|'([^']*)')/g, (_, key, double, single) => {
    if (Object.hasOwn(attrs, key)) corrupt();
    const value = double ?? single;
    if (value.includes('<') || /&(?!(?:amp|lt|gt|quot|apos|#\d+|#x[\da-f]+);)/i.test(value)) corrupt();
    attrs[key] = decode(value);
    return '';
  });
  if (rest.trim()) corrupt();
  return attrs;
}

function parseSliceInfo(xml: string, gcode: Map<number, string>) {
  if (xml.length > METADATA_SIZE_LIMIT) limit();
  const stack: string[] = [];
  const blocks: Array<{ meta: Record<string, string>; filament: Record<string, string>[] }> = [];
  let current: typeof blocks[number] | undefined;
  let rootSeen = false;
  let offset = 0;
  for (const match of xml.matchAll(/<\?[\s\S]*?\?>|<!--[\s\S]*?-->|<[^>]+>/g)) {
    if (xml.slice(offset, match.index).trim()) corrupt();
    offset = match.index! + match[0].length;
    const token = match[0];
    if (token.startsWith('<?') || token.startsWith('<!--')) continue;
    const name = token.match(/^<\/?([\w:.-]+)/)?.[1];
    if (!name || token.startsWith('<!')) corrupt();
    if (token.startsWith('</')) {
      if (stack.pop() !== name || !new RegExp(`^</${name}\\s*>$`).test(token)) corrupt();
      if (name === 'plate') current = undefined;
      continue;
    }
    if (!stack.length) {
      if (rootSeen || name !== 'config') corrupt();
      rootSeen = true;
    }
    const attrs = attributes(token);
    if (name === 'plate') {
      if (current) corrupt();
      current = { meta: Object.create(null), filament: [] };
      blocks.push(current);
    } else if (name === 'metadata' && current && attrs.key) {
      if (Object.hasOwn(current.meta, attrs.key) || attrs.value === undefined) corrupt();
      current.meta[attrs.key] = attrs.value;
    }
    else if (name === 'filament' && current) current.filament.push(attrs);
    if (!/\/\s*>$/.test(token)) stack.push(name);
    if (stack.length > 32) corrupt();
  }
  if (stack.length || !rootSeen || xml.slice(offset).trim()) corrupt();
  if (!blocks.length) throw new ParseFailure('no_slicing_data', 'Проєкт містить моделі, але не містить результату нарізки.');
  return blocks.map(({ meta, filament }) => {
    const index = number(meta.index);
    if (index === undefined) corrupt();
    const text = gcode.get(index);
    let fallback: ReturnType<typeof parseGcode> | undefined;
    if (text) { try { fallback = parseGcode(text, index, parseDuration(meta.prediction)); } catch (error) { if (!(error instanceof ParseFailure) || error.status !== 'error') throw error; } }
    const filaments = filament.map((f): ParsedFilamentLayer => {
      const trayId = number(f.id);
      if (trayId === undefined) incomplete();
      const match = fallback?.plate.filaments.find((layer) => layer.trayId === trayId);
      const weight = number(f.used_g) ?? match?.weightGrams;
      const length = number(f.used_m) ?? match?.lengthMeters;
      if (weight === undefined || f.used_g !== undefined && number(f.used_g) === undefined || f.used_m !== undefined && number(f.used_m) === undefined) incomplete();
      return { trayId, type: f.type || match?.type || 'Невідомий', colorHex: color(f.color ?? match?.colorHex), weightGrams: weight, ...(length !== undefined ? { lengthMeters: length } : {}) };
    });
    return { plate: plate(index, parseDuration(meta.prediction) ?? fallback?.plate.predictionSeconds, filaments.length ? filaments : fallback?.plate.filaments ?? []), source: fallback?.source ?? 'Bambu Studio / OrcaSlicer (slice_info.config)', printer: meta.printer_model_id ?? fallback?.printer, nozzle: meta.nozzle_diameters ?? fallback?.nozzle };
  });
}

const crcTable = Uint32Array.from({ length: 256 }, (_, i) => {
  let value = i;
  for (let bit = 0; bit < 8; bit++) value = value & 1 ? 0xedb88320 ^ value >>> 1 : value >>> 1;
  return value >>> 0;
});

export function readPrintArchive(data: Uint8Array) {
  const view = new DataView(data.buffer, data.byteOffset, data.byteLength);
  let end = data.length - 22;
  for (; end >= Math.max(0, data.length - 65557); end--) {
    if (view.getUint32(end, true) === 0x06054b50 && end + 22 + view.getUint16(end + 20, true) === data.length) break;
  }
  if (end < Math.max(0, data.length - 65557)) corrupt();
  const count = view.getUint16(end + 10, true);
  if (count > 2048) limit();
  if (view.getUint16(end + 4, true) || view.getUint16(end + 6, true) || view.getUint16(end + 8, true) !== count) corrupt();
  let cursor = view.getUint32(end + 16, true);
  const centralEnd = cursor + view.getUint32(end + 12, true);
  if (centralEnd !== end) corrupt();
  let total = 0;
  const files = new Map<string, string>();
  const names = new Set<string>();
  for (let entry = 0; entry < count; entry++) {
    if (cursor + 46 > centralEnd || view.getUint32(cursor, true) !== 0x02014b50) corrupt();
    const flags = view.getUint16(cursor + 8, true);
    const method = view.getUint16(cursor + 10, true);
    const crc = view.getUint32(cursor + 16, true);
    const compressed = view.getUint32(cursor + 20, true);
    const size = view.getUint32(cursor + 24, true);
    const nameSize = view.getUint16(cursor + 28, true);
    const next = cursor + 46 + nameSize + view.getUint16(cursor + 30, true) + view.getUint16(cursor + 32, true);
    const local = view.getUint32(cursor + 42, true);
    if (next > centralEnd || local + 30 > view.getUint32(end + 16, true)) corrupt();
    if (size > ENTRY_SIZE_LIMIT || compressed > FILE_SIZE_LIMIT || (total += size) > ARCHIVE_SIZE_LIMIT) limit();
    const name = decoder.decode(data.subarray(cursor + 46, cursor + 46 + nameSize)).replace(/\\/g, '/');
    if (names.has(name) || flags & 1 || method !== 0 && method !== 8) corrupt();
    names.add(name);
    if (view.getUint32(local, true) !== 0x04034b50 || view.getUint16(local + 8, true) !== method || view.getUint16(local + 6, true) !== flags) corrupt();
    const localNameSize = view.getUint16(local + 26, true);
    const start = local + 30 + localNameSize + view.getUint16(local + 28, true);
    if (start + compressed > view.getUint32(end + 16, true) || decoder.decode(data.subarray(local + 30, local + 30 + localNameSize)).replace(/\\/g, '/') !== name) corrupt();
    if (!(flags & 8) && (view.getUint32(local + 18, true) !== compressed || view.getUint32(local + 22, true) !== size || view.getUint32(local + 14, true) !== crc)) corrupt();
    cursor = next;
    if (!/^Metadata\/(?:slice_info\.config|plate_\d+\.gcode)$/i.test(name) && !/\.gcode$/i.test(name)) continue;
    if (/slice_info\.config$/i.test(name) && size > METADATA_SIZE_LIMIT) limit();
    const output = new Uint8Array(size);
    let written = 0;
    let checksum = 0xffffffff;
    const accept = (chunk: Uint8Array) => {
      if (written + chunk.length > size) corrupt();
      output.set(chunk, written);
      written += chunk.length;
      for (const byte of chunk) checksum = crcTable[(checksum ^ byte) & 255] ^ checksum >>> 8;
    };
    if (!method) accept(data.subarray(start, start + compressed));
    else {
      const inflate = new Inflate(accept);
      for (let offset = 0; offset < compressed; offset += 1024) inflate.push(data.subarray(start + offset, start + Math.min(offset + 1024, compressed)), offset + 1024 >= compressed);
    }
    if (written !== size || (checksum ^ 0xffffffff) >>> 0 !== crc) corrupt();
    files.set(name, decoder.decode(output));
  }
  if (cursor !== centralEnd) corrupt();
  return { files, names };
}

export function parsePrintFile(fileName: string, data: Uint8Array, fileSizeBytes = data.length): ParsedJob {
  const job: ParsedJob = { fileName, fileSizeBytes, slicerSource: 'Невідомо', plates: [], totalPredictionSeconds: 0, totalWeightGrams: 0, warnings: [], parseStatus: 'error' };
  try {
    if (fileSizeBytes > FILE_SIZE_LIMIT) limit();
    let parsed: ReturnType<typeof parseGcode>[];
    if (/\.gcode$/i.test(fileName)) parsed = [parseGcode(decoder.decode(data), 1)];
    else if (/\.3mf$/i.test(fileName)) {
      const { files, names } = readPrintArchive(data);
      const sliceInfo = [...files].find(([name]) => /^Metadata\/slice_info\.config$/i.test(name))?.[1];
      const gcode = new Map<number, string>();
      const gcodeFiles = [...files].filter(([name]) => /\.gcode$/i.test(name));
      for (const [name, text] of gcodeFiles) {
        const index = Number(name.match(/(?:^|\/)plate_(\d+)\.gcode$/i)?.[1] ?? (gcodeFiles.length === 1 ? 1 : NaN));
        if (!Number.isInteger(index) || index < 1 || gcode.has(index)) incomplete();
        gcode.set(index, text);
      }
      if (sliceInfo) {
        parsed = parseSliceInfo(sliceInfo, gcode);
        const declared = new Set(parsed.map((item) => item.plate.plateIndex));
        if ([...gcode.keys()].some((index) => !declared.has(index))) incomplete();
      } else if (gcode.size) parsed = [...gcode].map(([index, text]) => parseGcode(text, index));
      else if ([...names].some((name) => /^3D\/.*\.model$/i.test(name))) throw new ParseFailure('no_slicing_data', 'Проєкт містить моделі, але не містить результату нарізки. Експортуйте нарізаний .gcode.3mf або текстовий .gcode.');
      else throw new ParseFailure('error', 'Архів не містить підтримуваних метаданих нарізки Bambu Studio / OrcaSlicer.');
    } else throw new ParseFailure('error', 'Підтримуються текстовий .gcode та нарізані .3mf / .gcode.3mf. Binary .bgcode і моделі .stl не підтримуються.');
    if (new Set(parsed.map((item) => item.plate.plateIndex)).size !== parsed.length) corrupt();
    job.plates = parsed.map((item) => item.plate).sort((a, b) => a.plateIndex - b.plateIndex);
    job.slicerSource = [...new Set(parsed.map((item) => item.source))].join(', ');
    const printer = parsed.find((item) => item.printer)?.printer;
    const nozzle = parsed.find((item) => item.nozzle)?.nozzle;
    if (printer) job.printerModelName = printer;
    if (nozzle) job.nozzleDiameterMm = nozzle;
    job.totalPredictionSeconds = job.plates.reduce((sum, p) => sum + p.predictionSeconds, 0);
    job.totalWeightGrams = job.plates.reduce((sum, p) => sum + p.totalWeightGrams, 0);
    if (!Number.isFinite(job.totalPredictionSeconds) || !Number.isFinite(job.totalWeightGrams)) incomplete();
    if (job.plates.some((p) => p.filaments.some((f) => f.type === 'Невідомий'))) job.warnings.push('Тип частини філаментів відсутній у файлі. Виберіть матеріали вручну.');
    if (job.plates.some((p) => p.filaments.some((f) => f.colorHex === '#808080'))) job.warnings.push('Для кольорів, яких немає у файлі, показано сірий колір.');
    job.parseStatus = 'success';
  } catch (error) {
    job.plates = [];
    job.totalPredictionSeconds = 0;
    job.totalWeightGrams = 0;
    job.parseStatus = error instanceof ParseFailure ? error.status : 'corrupted';
    job.errorMessage = error instanceof ParseFailure ? error.message : 'Не вдалося прочитати файл: пошкоджені дані або непідтримуване кодування.';
  }
  return job;
}
