import assert from 'node:assert/strict';
import { test } from 'node:test';
import { strToU8, zipSync } from 'fflate';
import { FILE_SIZE_LIMIT, parseDuration, parsePrintFile } from '../src/services/printFileParser.ts';
import { fileAnalysisService } from '../src/services/fileAnalysisService.ts';

const gcode = `; generated by PrusaSlicer 2.9.2
; filament used [mm] = 10000, 5000
; filament used [g] = 30, 15
; estimated printing time (normal mode) = 1h 2m 3s
; filament_type = PLA;PETG
; filament_colour = #123456;#abcdef
; printer_model = MK4
; nozzle_diameter = 0.4
G1 X20 E1
`;
const parseText = (text: string) => parsePrintFile('part.gcode', strToU8(text));
const archive = (entries: Record<string, string>) => zipSync(Object.fromEntries(Object.entries(entries).map(([name, text]) => [name, strToU8(text)])));
const xml = (plates: string) => `<?xml version="1.0" encoding="UTF-8"?><config><header><header_item key="X-BBL-Client-Version" value="02.03"/></header>${plates}</config>`;
const plate = (index: number, prediction = '3600', filament = '<filament id="3" type="PETG" color="#ABCDEF80" used_g="20.5" used_m="6.5"/>') => `<plate><metadata key="index" value="${index}"/><metadata key="prediction" value="${prediction}"/><metadata key="printer_model_id" value="P1S"/>${filament}</plate>`;

test('parses actual plain G-code metadata and per-tray usage', () => {
  const parsed = parseText(gcode);
  assert.equal(parsed.parseStatus, 'success');
  assert.equal(parsed.totalPredictionSeconds, 3723);
  assert.equal(parsed.totalWeightGrams, 45);
  assert.equal(parsed.printerModelName, 'MK4');
  assert.deepEqual(parsed.plates[0].filaments.map((f) => [f.trayId, f.type, f.colorHex, f.weightGrams, f.lengthMeters]), [[1, 'PLA', '#123456', 30, 10], [2, 'PETG', '#abcdef', 15, 5]]);
  assert.equal(parseText(gcode.replace(/\n/g, '\r\n')).totalWeightGrams, 45);
});

test('reads Bambu/Orca archive indices and sparse filament IDs without mixing plates', () => {
  const bytes = archive({ 'Metadata/slice_info.config': xml(plate(4, '7200') + plate(2, '1800', '<filament id="1" type="PLA" color="#000000" used_g="10" used_m="3"/><filament id="4" type="ABS" color="#FFFFFF" used_g="5" used_m="2"/>')), 'Metadata/plate_4.gcode': 'G1 X1', 'Metadata/plate_2.gcode': 'G1 X2', '3D/3dmodel.model': '<model/>' });
  const parsed = parsePrintFile('multiple.gcode.3mf', bytes);
  assert.equal(parsed.parseStatus, 'success', parsed.errorMessage);
  assert.equal(parsed.totalPredictionSeconds, 9000);
  assert.equal(parsed.totalWeightGrams, 35.5);
  assert.deepEqual(parsed.plates.map((p) => [p.plateIndex, p.filaments.map((f) => f.trayId)]), [[2, [1, 4]], [4, [3]]]);
  assert.equal(parsed.plates[1].filaments[0].colorHex, '#ABCDEF');
});

test('can read archived G-code without slice_info and Bambu plain header stats', () => {
  const parsed = parsePrintFile('single.3mf', archive({ 'Metadata/plate_3.gcode': gcode }));
  assert.equal(parsed.parseStatus, 'success');
  assert.equal(parsed.plates[0].plateIndex, 3);
  const bambu = parseText('; model printing time: 1h; total estimated time: 1h 10m\n; total filament weight [g] : 12.3\n; filament_type = PLA\n');
  assert.equal(bambu.parseStatus, 'success');
  assert.equal(bambu.totalPredictionSeconds, 4200);
  assert.equal(bambu.totalWeightGrams, 12.3);
});

test('rejects corrupt archives and distinguishes unsliced models', () => {
  assert.equal(parsePrintFile('bad.3mf', strToU8('not a zip')).parseStatus, 'corrupted');
  assert.equal(parsePrintFile('bad.3mf', new Uint8Array()).parseStatus, 'corrupted');
  assert.equal(parsePrintFile('model.3mf', archive({ '3D/3dmodel.model': '<model/>' })).parseStatus, 'no_slicing_data');
  assert.equal(parsePrintFile('other.3mf', archive({ 'unknown.txt': 'text' })).parseStatus, 'error');
  assert.equal(parsePrintFile('bad.3mf', archive({ 'Metadata/slice_info.config': xml(plate(1)).replace('</plate>', '</wrong>') })).parseStatus, 'corrupted');
});

test('missing weights/time and ambiguous packed tray arrays never succeed', () => {
  for (const text of [gcode.replace(/; estimated printing time[^\n]+\n/, ''), gcode.replace(/; filament used \[(?:mm|g)\][^\n]+\n/g, ''), '; estimated printing time (normal mode) = 1h\n; filament used [mm] = 1000', '; total estimated time: 1h\n; total filament weight [g] : 12\n; filament_type = PLA;PETG']) {
    const parsed = parseText(text);
    assert.equal(parsed.parseStatus, 'error');
    assert.equal(parsed.plates.length, 0);
  }
  assert.equal(parsePrintFile('missing.3mf', archive({ 'Metadata/slice_info.config': xml(plate(1, '')) })).parseStatus, 'error');
  assert.equal(parsePrintFile('missing.3mf', archive({ 'Metadata/slice_info.config': xml(plate(1, '3600', '<filament id="1" type="PLA" used_m="10"/>')) })).parseStatus, 'error');
});

test('mass conversion requires real density and diameter, never a type default', () => {
  const parsed = parseText('; estimated printing time (normal mode) = 2m\n; filament used [mm] = 1000\n; filament_density = 1.24\n; filament_diameter = 1.75\n; filament_type = PLA');
  assert.equal(parsed.parseStatus, 'success');
  assert.ok(Math.abs(parsed.totalWeightGrams - Math.PI * (1.75 / 2) ** 2 * 1.24) < 1e-9);
  const zipped = parsePrintFile('length.3mf', archive({ 'Metadata/slice_info.config': xml(plate(1, '120', '<filament id="1" type="PLA" used_m="1"/>')), 'Metadata/plate_1.gcode': '; filament used [mm] = 1000\n; filament_density = 1.24\n; filament_diameter = 1.75\n; filament_type = PLA' }));
  assert.equal(zipped.parseStatus, 'success', zipped.errorMessage);
  assert.equal(zipped.totalWeightGrams, parsed.totalWeightGrams);
});

test('ZIP size, count, checksum and actual inflation are bounded', () => {
  assert.equal(parsePrintFile('large.gcode', new Uint8Array(), FILE_SIZE_LIMIT + 1).parseStatus, 'file_limit_exceeded');
  const bytes = archive({ 'Metadata/plate_1.gcode': gcode });
  const large = bytes.slice();
  const central = new DataView(large.buffer).getUint32(large.length - 6, true);
  new DataView(large.buffer).setUint32(central + 24, 64 * 1024 * 1024 + 1, true);
  assert.equal(parsePrintFile('large.3mf', large).parseStatus, 'file_limit_exceeded');
  const count = bytes.slice();
  new DataView(count.buffer).setUint16(count.length - 12, 2049, true);
  assert.equal(parsePrintFile('count.3mf', count).parseStatus, 'file_limit_exceeded');
  const wrongCrc = bytes.slice();
  new DataView(wrongCrc.buffer).setUint32(14, 0, true);
  new DataView(wrongCrc.buffer).setUint32(central + 16, 0, true);
  assert.equal(parsePrintFile('crc.3mf', wrongCrc).parseStatus, 'corrupted');
  const wrongSize = bytes.slice();
  new DataView(wrongSize.buffer).setUint32(22, 1, true);
  new DataView(wrongSize.buffer).setUint32(central + 24, 1, true);
  assert.equal(parsePrintFile('bomb.3mf', wrongSize).parseStatus, 'corrupted');
});

test('time formats and explicitly labelled demo scenarios', async () => {
  assert.equal(parseDuration('1d 2h 3m 4s'), 93784);
  assert.equal(parseDuration('02:03:04'), 7384);
  assert.equal(parseDuration('2h junk'), undefined);
  assert.equal(parseDuration('02:99:04'), undefined);
  const demo = await fileAnalysisService.loadPresetJob('multi_plate');
  assert.equal(demo.isDemoJob, true);
  assert.equal(demo.plates.length, 2);
  assert.equal(demo.totalWeightGrams, 300);
  assert.equal((await fileAnalysisService.loadPresetJob('no_slicing')).parseStatus, 'no_slicing_data');
  assert.equal((await fileAnalysisService.loadPresetJob('corrupted')).parseStatus, 'corrupted');
});

test('upload service reads the supplied file without substituting demo data', async () => {
  const actual = await fileAnalysisService.analyzeUploadedFile(new File([gcode], 'actual.gcode'));
  assert.equal(actual.totalWeightGrams, 45);
  assert.equal(actual.isDemoJob, undefined);
  const bad = await fileAnalysisService.analyzeUploadedFile(new File(['bad archive'], 'actual.3mf'));
  assert.equal(bad.parseStatus, 'corrupted');
  assert.equal(bad.totalWeightGrams, 0);
});
